### PR TITLE
WIP: Added initial man page

### PR DESCRIPTION
**Pull request by rickard-von-essen**
This is a rough cut on a man page for xhyve. I'll detail some of the shortcomings in a comment..

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
Things that should be sorted out/fixed:
1. line 42: Flag ```-f firmware``` should not be optional
2. line 65: ```device bvmconsole``` this is not correct for OS X?
3. line 81: ```device bvmdebug``` this is not correct for OS X?
4. line 257: How is ```UUID``` generated, probably not from vmname?
5. line 270: Explain flag ```-f firmware```

**Comment by rickard-von-essen** [comment]
After this have been merged these things should also be fixed:
- Update Makefile and brew recipe

Maybe remove deprecated and debug flags detailed descriptions from the help text and point to the man page.

**Comment by jeremyhu** [comment]
This was merged into https://github.com/xhyve-xyz/xhyve

**Comment by mist64** [comment]
Very cool. I would love it if you kept updating it. :D

**Pull request merged**
