### PR TITLE
Adds option to create master/slave pseudo-terminals when adding LPC devices.

### PR DESCRIPTION
**Pull request by c4milo**
Enables to easily access xhyve guests through serial terminals. Demo: https://cldup.com/enMVXo6vKA.gif

For those unfamiliar with ptmx, there is a great explanation at http://unix.stackexchange.com/a/120018/128551

### CODE REVIEW

**Comment by xez** [comment]
👍 cool

**Comment by jeremyhu** [comment]
This was merged into https://github.com/xhyve-xyz/xhyve

**Comment by c4milo** [comment]
@mist64 done.

**Comment by c4milo** [comment]
@xez, any chance you could get this merged?

**Comment by xez** [comment]
@c4milo Sure, but it currently has merge conflicts :(

**Comment by c4milo** [comment]
Hm, I will work through them tomorrow.

**Comment by c4milo** [comment]
I just resolved the conflicts @xez. Feel free to merge whenever you have some time.

**Comment by xez** [comment]
:thumbsup:

**Comment by c4milo** [comment]
\o/ thanks!

**Pull request merged**
