### PR TITLE
Add support for FreeBSD guests

### PR DESCRIPTION
**Pull request by xez**
fbsd
Hello, FreeBSD!

### CODE REVIEW

**Comment by AntonioMeireles** [comment]
+1

**Comment by rimusz** [comment]
+1

**Comment by colby-swandale** [comment]
superstar, thank you!

**Comment by AntonioMeireles** [comment]
@xez  (curious) btw any progresses towards mergeability in your tap stuff ?

**Comment by davidchisnall** [comment]
Are there instructions somewhere for installing FreeBSD into an xhyve VM?

**Comment by xez** [comment]
@davidchisnall 

You can, for example, download the pre-built raw FreeBSD VM image and modify `xhyverun.sh` to:

    #!/bin/sh
    
    # FreeBSD
    USERBOOT="test/userboot.so"
    BOOTVOLUME="/somepath/FreeBSD-10.1-RELEASE-amd64.raw"
    KERNELENV=""
    
    MEM="-m 1G"
    #SMP="-c 2"
    NET="-s 2:0,virtio-net"
    #IMG_CD="-s 3,ahci-cd,/somepath/somefile.iso"
    IMG_HDD="-s 4,virtio-blk,/somepath/FreeBSD-10.1-RELEASE-amd64.raw"
    PCI_DEV="-s 0:0,hostbridge -s 31,lpc"
    LPC_DEV="-l com1,stdio"
    ACPI="-A"
    UUID="-U deadbeef-dead-dead-dead-deaddeafbeef"
    
    # FreeBSD
    sudo build/xhyve $ACPI $MEM $SMP $PCI_DEV $LPC_DEV $NET $IMG_CD $IMG_HDD $UUID -f fbsd,$USERBOOT,$BOOTVOLUME,"$KERNELENV"

You could also create your own empty disk image and use the FreeBSD installation iso's instead.

**Pull request merged**
