### PR TITLE
Use strlcpy() instead of strncpy() because subsequent mkstemps expects the string be nul-terminated.

### PR DESCRIPTION
**Pull request by c4milo**
Back ports recent change from bhyve.

### CODE REVIEW

**Comment by c4milo** [comment]
Although, `acpi.c` doesn't seem to be used at all by xhyve.

**Comment by xez** [comment]
👍

**Comment by jeremyhu** [comment]
This was merged into https://github.com/xhyve-xyz/xhyve

**Comment by copumpkin** [comment]
@jeremyhu how does that repo compare to this one? Should the readme be amended if that's the main one?

**Comment by 07151129** [comment]
Can someone contact @mist64 and ask him to give the necessary permissions to e.g. @jeremyhu? It is unfavorable to have xhyve forked :(

**Comment by jeremyhu** [comment]
@mist64 has disappeared.  We've been trying to contact him for about 2 months to discuss this and never got a reply.  It seems that he has abandoned this, which is why we needed to start organizing on our own.

**Comment by gnawux** [comment]
@jeremyhu agree. it's better to have someone keep the project live than leave it dead. And I just sent a first PR to your xhyve-hxy project.

**Comment by mist64** [comment]
I'm not dead yet! :) 
I apologize for being unresponsive. I do plan to keep maintaining this project.

**Comment by copumpkin** [comment]
Yay!

**Pull request merged**
